name: Fetch Thumbnails

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write cookies file
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install yt-dlp with curl-cffi
        run: pip install "yt-dlp[default,curl-cffi]"

      - name: Run thumbnail script
        run: python scripts/fetch_thumbnails.py

      - name: Commit thumbnails
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add thumbnails
          git commit -m "Update thumbnails" || echo "No changes"
          git push
