name: Fetch YouTube Subtitles

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write cookies file
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt


      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install yt-dlp
        run: pip install -U "yt-dlp[default,curl-cffi]"

      - name: Debug subtitle availability
        run: |
          yt-dlp \
            --cookies cookies.txt \
            --list-subs \
            https://www.youtube.com/watch?v=$(jq -r '.[0]' data/streams.json)

      - name: Create subtitles folder
        run: mkdir -p subtitles

      - name: Create livechat folder
        run: mkdir -p livechat

      - name: Run subtitle script
        run: bash scripts/fetch_subtitles.sh

      - name: Commit generated data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add subtitles
          git add livechat
          git add timeline
          git add timeline_chunks

          git commit -m "Update archive data" || echo "No changes"

          git pull --rebase origin Main-dayo
          git push origin Main-dayo
